# Generated by Django 3.2 on 2021-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.IntegerField()),
                ('average_rating', models.IntegerField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(related_name='book_authors', to='website.Author')),
                ('categories', models.ManyToManyField(related_name='book_categories', to='website.Category')),
            ],
        ),
    ]
