# Generated by Django 3.0.6 on 2021-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('published_date', models.IntegerField()),
                ('average_rating', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=255)),
            ],
        ),
    ]
